### ISSUE TITLE
0.18.0 release to pub.dev?

### ISSUE THREAD

**Issue by StephenWithPH** [Workiva/opentelemetry-dart#142]
First, thank you for maintaining and open-sourcing this!

I see #141 , which looks like part of the release ceremony for a v0.18.0. Of note, pubspec.yaml is still on 0.17.0: https://github.com/Workiva/opentelemetry-dart/blob/0c9c0cf7401967f7c7bf146f6fd99426174d79be/pubspec.yaml#L2

Do you plan on publishing 0.18.0 to pub.dev?

**Comment by blakeroberts-wk** [comment]
Hey @StephenWithPH

Sorry about this, this was an accident. We plan on publishing 0.18.0. It may need to be 0.18.1. We are working on publishing.

**Comment by michaelyeager-wf** [comment]
👋 @StephenWithPH 

This is to let you know that we've published 0.18.0 and it should be available for you. 
https://pub.dev/packages/opentelemetry/versions/0.18.0

Thanks for filing this issue!
