### ISSUE TITLE
Context.current.span doesn't find the current span 

### ISSUE THREAD

**Issue by constantberthereau** [Workiva/opentelemetry-dart#166]
I don't know if it's a real problem or a mistake, but i'm trying to close a span without store span in a variable. 

Here is my code:

    CollectorExporter exporter = otel_sdk.CollectorExporter(
      Uri.parse("https://test/v1/traces"),
    );
    BatchSpanProcessor processor = otel_sdk.BatchSpanProcessor(exporter);
    SimpleSpanProcessor simpleProcessor =
        otel_sdk.SimpleSpanProcessor(otel_sdk.ConsoleExporter());
    TracerProvider provider = otel_sdk.TracerProviderBase(
      processors: <otel_sdk.SpanProcessor>[processor, simpleProcessor],
      resource: otel_sdk.Resource(<Attribute>[
        Attribute.fromString("service.name", name),
        Attribute.fromString("telemetry.sdk.version", "1.6.0"),
        Attribute.fromString("telemetry.sdk.name", "opentelemetry"),
      ]),
    );
    registerGlobalTracerProvider(provider);

    Span span= globalTracerProvider.getTracer('Mobilité').startSpan(
          'parentSpan',
        );

    await Future.delayed(const Duration(seconds: 3));

    Context.current.span.end(); 

I think, the problem come from Context.current.span. It doesn't find the span in the current context.

**Comment by constantberthereau** [comment]
Hi, the issue isn't fixed. When i call `Context.current.withSpan(span);` (i need to pass through the current method because withSpan isn't static) it doesn't store any value in the current context, it just return a new Context. So do i need to store in my code a Context ?

I just try another way, i used the exemple in the README like this : 
  static Future<void> startListeningTrace(String spanName) async {
    Span span =
        globalTracerProvider.getTracer('Mobilité').startSpan('doingWork');
    doWork();
    span.end();
  }

  static doWork() {
    Span parentSpan = Context.current.span;

    Context.current.withSpan(parentSpan).execute(() {
      Span span =
          globalTracerProvider.getTracer('Mobilité').startSpan('doWork');
      Future.delayed(const Duration(seconds: 3));
      span.end();
    });
  }

It create 2 spans, but isn't link. Both hasn't parent (i know just 1 could have a parent).

**Comment by jonathancampbell-wk** [comment]
Correct, `withSpan()` will only return a new context, there is not a way to update the current context with a new span. This is to match the [OpenTelemetry spec](https://opentelemetry.io/docs/specs/otel/context/#overview) that states that context must be immutable. Behind the scenes the Context API uses Dart Zones to propagate context between parent/child. This means that you must use the `execute()` function to run your child spans in a Context/Zone that is a child of the parent span.

In your example you would need to use `execute()` to run `doWork()` like below.

```
Future<void> startListeningTrace(String spanName) async {
  api.Span span = tracer.startSpan('doingWork');
  api.Context.current.withSpan(span).execute(() {
    doWork();
  });
  span.end();
}
```
