### ISSUE TITLE
Deprecate InstrumentationLibrary usages and use InstrumentationScope instead

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/opentelemetry-dart#98]
With PR #87 is merged, it introduces the  `InstrumentationScope` class that is intended to replace the `InstrumentationLibrary` class.  We will want to consolidate the existing usages to leverage the `InstrumentationScope` class.

**Comment by blakeroberts-wk** [comment]
Internal usage of `InstrumentationLibrary` has been updated to use `InstrumentationScope`.
